### ISSUE TITLE
Comments on script for first scene 

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/script-and-story-board#1]
# Script

### Inside PNN newsroom

*(News intro: "This is PNN Breaking News")*

**News Particle**: The series of electron and positron thefts at the central lepton storage room seems to continue. In a recently released statement, the Baryon family reached out to the thief. Within that statement, the family begs the thief to stop removing the leptons, as the youngest members of the Baryon family, Penelope Proton and Norman Neutron, are in desperate need of electrons to build their atoms.

*(Transition to lepton storage room)*

### Inside the lepton storage room

*(positron and electron annihilate, flash, particle appears out of nowhere; particle looks around cautiously)*

**J/&psi;:** All right, seems like the coast is clear.

*(particle turns to the viewer)*

**J/&psi;:** Hi, hi you! I'm on the run, so we have to keep it quiet, okay? I would like to introduce myself to you: My name is J/&psi; and I'm a particle. 
What! You never heard of me? Well, I don't even know where to start in that case.
Let's talk about the particle part again. You must think of a particle as a tiny amount of matter. However not in the sense of for example a particle of dust, but even smaller. And there is a ton of us! You maybe already heard of Penelope Proton and the Norman Neutron. 

*(proton and neutron appear on screen)*

All the matter that surrounds you, every atom is made up of protons, neutrons and electrons. I'm sure you've already heard of the hydrogen atom, right? It consists of one proton and one electron! You see, you do know something about particles. 

**J/&psi;:** Now you might think: "They make up all the matter that surrounds me? But I can't see any particles!"
 Well, that is because they are so tiny that you can't possibly see them with the bare eye. They are even smaller than dust particles. And on top of that, if you take the proton and the neutron, they consist of even smaller constituents which are referred to as quarks. 

*(quarks appear on screen)*

**J/&psi;:** To be more specific, the quarks that make up the proton and neutron are called up- and down-quarks. On the other hand, the electron that appears in an atom is part of a group called leptons. Quarks and leptons occur in three different generations. For quarks in each generation, there are two different flavours. For example the up- and down-flavoured quarks in the first generation.

*(highlight up and down quark)*

**J/&psi;:** These are the quarks Penelope and Norman are made up of. I am also built by quarks, but they belong to the second generation and are called charm quarks...

*(highlight charm and strange quarks)*

**J/&psi;:** There are also top and bottom quarks and the quark mass increases with every generation. It is similar in the case of the leptons. The electron has two other relatives, that are exact copies in most of its characteristics, but with increasing mass. So the third generation lepton is heavier than the second generation lepton that is heavier than the first generation lepton. This mass hierarchy however is not apparent in the three other leptons, called neutrinos. They seem to be massless and practically invisible. The quarks and leptons are elementary particles, which means we can build a ton of other particles with them, like the proton and neutron and even me! Let's have a closer look at that: 

*(some kind of zoom-in/animation inside the proton and neutron ?)*

You now know that proton and neutron are built by up- and down-quarks. And their quark content also helps us to differentiate between those two particles. The proton has two up-quarks and one down-quark. For the neutron, it's just the other way around. It consists of two up-quarks and one down-quark.
So, now you understand how Penelope and Norman are formed.
In comparison to Penelope and Norman, I only consist of two quarks, namely the charm quarks.
This is common to all members of my family. In the Meson family, every particle consists of two quarks. All particles that consist of three quarks however are called baryons. And do you know how many baryons and mesons there are? A lot, in fact, there are so many that a whole zoo of particles exist!

*(some kind of zoo illustration with particles :D )*

**J/&psi;:** "But how do we know", you ask yourself? "How we know that there exist particles when we can't even see those particles?"
Well, there are ways to make them visible. Take this bubble chamber for example. 

*(some kind of bubble chamber illustration)*

You can see several tracks here. Some of them are curved, some are straight. Every single track belongs to a particle. Some of the tracks are produced by mesons, that travel through the liquid in this chamber. Some are created by electrons and so on. This is one of the most basic ways to make some particles visible. But you will learn more about that on the course of our adventure. 

Before we start there is still one thing I have to tell you about my world. 
My family, the meson family is very humble and down to earth. Unlike the Baryons who, just because they have one quark more are very arrogant and bigheaded. I cannot stand them at all! 
And I can assure you this feeling is mutual. The Baryons condemn us for getting in trouble too often and being some sort of criminals since my strange cousin Kaon was arrested for CP-violation. 

*(flashback of Kaon arrest by __PNN__ (Particle News Network))*

### Inside PNN newsroom

**News Particle**: Good evening ladies and gentleman. Welcome to our Breaking news special, where we keep you up to date about everything important that is happening in these turbulent times.
We were informed that, right now, the particle police is arresting the Kaon. It is being accused of direct CP-violation and there is strong evidence, that the Kaon is one of the particles responsible for this criminal act.

### Inside lepton storage room
**J/&psi;:** Listen I know, this sounds bad, but whatever the baryons tell you about us, don't -

*(Door to lepton storage room clicks, the particle is alarmed and vanishes in a flash of light)*

**Comment by s6nadavi** [comment]
Btw, this a bubble chamber image as mentioned in the text, for reference. The chamber is filled with liquid hydrogen and incoming particles react with the proton in the hydrogen. As charged particles pass through, they ionise the liquid. The tracks of the particles become visible as trails of (tiny) bubbles, which can be photographed.

![bubble_chamber_tracks](https://user-images.githubusercontent.com/73640699/115768542-bd433c00-a3aa-11eb-85ee-cdca0e583cf7.jpeg)

https://cds.cern.ch/record/39474

**Comment by Layfully** [comment]
I've just read it all and I think that story and dialogues are great! Altough I am worried that there is a lot of information to process. I had to reread some parts to get rough idea of how everthing works. I think it would be good idea to give user access to what has been told before. For example we could include text descriptions similiar to what we had in the teaser. Also I dont know what CP-violation is. Is it something that user should know? I don't really get what leptons are. How do they differ from quarks? The relation in mass is also confusing from text, but I think that models of particles are designed with this in mind so for example heavy particles are fatter and lighter are slimmer, am I right about that? I also asked Adam to give feedback on this and I will also ask professors and students from my english class.

**Comment by melbiel** [comment]
My suggestions/remarks on the scrip:

„Well, that is because they are so tiny that you can't possibly see them with the bare eye ”
suggests that they could be seen with some kind of apperatus. Maybe say "Well, that is because they are so tiny that you can't possibly see them"

When talking about the quarks, maybe tell something about the decay of the heavier quarks, so only up and down exist. Maybe talk about charges, not about 1/3 or 2/3 elementary charges, just positive and negative charges.

„They seem to be massless and practically invisible”
Maybe unorbservable instead of invisible.

„And their quark content also helps us to differentiate between those two particles ” -> charge

„This is common to all members of my family...” -> „This is common to all members of my family  - the meson family. Here every particle consist of two quark, while in the baryon family all members are made up of three quarks.”

„Well, there are ways to make them visible.”  
->”Well, there are ways to know if they were around.” (general problem with visibility of particles in this part. The part about the bubble chamber)

**Comment by DominiqueMClark** [comment]
I thought the script was great! The information that is given is perfect, just a little too condensed for the audience we are going for. My suggestion would be to add some sort of dialogue between J/ψ and the quarks that could really extend the explanation of the quarks. Maybe silly jokes, or funny questions that a viewer might ask but instead with a twist so that all the attention isn't all on us (the viewer) to make it feel like we are really immersed in another world. 

The only other nit-picky thing I would add is the line:
"The proton has two up-quarks and one down-quark. For the neutron, it's just the other way around. It 
         consists of two up-quarks and one down-quark." 
I do not know if it is a typo or if that is how it actually is but the make up of the two particles did not change but J/ψ says it is the other way around.

**Comment by s6nadavi** [comment]
# Script

## First Scene

### Part 1: Inside PNN newsroom

*(News intro: "This is PNN Breaking News", Bubble Chamber animation in the background, breaking news lettering floats in)*

**News Particle**: The series of electron and positron thefts at the central lepton storage room seems to continue. In a recently released statement, the Baryon family reached out to the thief. Within that statement, the family begs the thief to stop removing the leptons, as the youngest members of the Baryon family, Penelope Proton and Norman Neutron, are in desperate need of electrons to build their atoms.

*(atom building animation on news screen in the back)*

*(Transition to lepton storage room)*


### Part 2: Inside the lepton storage room

#### Section 1: Introduction

*(positron and electron annihilate, flash, particle appears out of nowhere; particle looks around cautiously)*

**J/&psi;:** All right, seems like the coast is clear.

*(particle turns to the viewer)*

**J/&psi;:** Hi, hi you! I'm on the run, so we have to keep it quiet, okay? I would like to introduce myself to you: My name is J/&psi; and I'm a particle. 
What! You never heard of me? Well, I don't even know where to start in that case. 
Let me give you a short explanation of how my world works. 

*(explanation of different sections, where to click, etc.)*

Now if you are wondering what a particle is, and what this adventure is all about, then click right here.

*(The next sections provide short explanations of one aspect of the particle world and will be individually accessible for the viewer.)*

#### Section 2: Particles
Hello again! Let's talk about elementary particles. You must think of a particle as a tiny amount of matter. However not in the sense of for example a particle of dust, but even smaller. 

*(show a zoom-in of daily life, small matter (dust particle, hair, etc. into the atomic scale. Zoom stops at the atomic nucleus.)*

And there is a ton of us! You maybe already heard of Penelope Proton and the Norman Neutron. 

*(proton and neutron appear on screen)*

All the matter that surrounds you, every atom is made up of protons, neutrons and electrons. I'm sure you've already heard of the hydrogen atom, right? 

*(Show hydrogen atom animation from part 1.)*

It consists of one proton and one electron! You see, you do know something about particles. But if we want to learn about the truly elementary particles, we have to take a closer look at the nucleons, the proton and the neutron again. To find out what these two are made up of check out the next section. 

#### Section 3: Quarks

**J/&psi;:** Now you might think: "These particles are supposed to make up all the matter that surrounds me? But I can't see any particles!"
 Well, that is because they are so tiny that you can't possibly see them. They are even smaller than dust particles. And on top of that, if you take the proton and the neutron, they consist of even smaller constituents which are referred to as quarks. 

*(quarks appear on screen)*

**J/&psi;:** To be more specific, the quarks that make up the proton and neutron are called up- and down-quarks. 
Let's have the Up-quark explain this to us in more detail.

*(up-quark joins J/&psi;:, starts explaining )*

**Up-Quark:** Hi everybody, I am an Up-Quark. Us Quarks occur in three different generations. For quarks in each generation, there are two different flavours. In my generation for example, there are quarks like me, that are up-flavoured, as well as quarks that are down-flavoured.

*(highlight down quark)*

**J/&psi;:** Yes, these two are the quarks Penelope and Norman are made up of. Thanks for helping me out 'Up'!
I am also built by quarks, but they belong to the second generation of quarks. Carry on to the next section, to learn about all the other quarks that exist!

#### Section 4 Higher generation Quarks and Leptons

So, let's have a look at the second generation of quarks. It consists of the quarks I am built of, the charm quarks. The other flavour of the second generation is referred to as strange-quark. 

*(highlight charm and strange quarks)*

**J/&psi;:** There are also top and bottom quarks and the quark mass increases with every generation. It is similar in the case of a second particle family, the leptons. One of its members you already know: the electron. The electron has two other relatives, that are exact copies in most of its characteristics, but with increasing mass. So the third generation lepton is heavier than the second generation lepton that is heavier than the first generation lepton. This mass hierarchy however is not apparent in the three other leptons, called neutrinos. They seem to be massless and practically undetectable. The quarks and leptons are elementary particles, which means we can build a ton of other particles with them, like the proton and neutron and even me! Let's have a closer look at that in the next section!

#### Section 5 Mesons and Baryons

*(some kind of zoom-in/animation inside the proton and neutron ?)*

You now know that proton and neutron are built by up- and down-quarks. And their quark content also serves as a way to differentiate between those two particles. The proton has two up-quarks and one down-quark. For the neutron, it's just the other way around. It consists of two down-quarks and one up-quark. The different quark content of the nucleons also influences their electric charge. Because of the majority of positively charged up-quarks, the proton has a positive charge. Since there are more negatively charged down-quarks inside the neutron it has a resulting negative charge. That's another way to distinguish between proton and neutron! 
So, now you understand how Penelope and Norman are formed.
In comparison to Penelope and Norman, I only consist of two quarks, namely the charm quarks.
This is common to all members of my family, the Meson family. Here every particle consists of two quarks, while in the Baryon family all members are made up of three quarks. And do you know how many baryons and mesons there are? A lot, in fact, there are so many that a whole zoo of particles exist!

*(some kind of zoo illustration with particles :D )*

#### Section 6 Particle Detection

**J/&psi;:** "But how do we know", you ask yourself? "How we know that there exist particles when we can't even see those particles?"
Well, there are ways to prove that they are around. Take this bubble chamber for example. 

*(some kind of bubble chamber illustration)*

You can see several tracks here. Some of them are curved, some are straight. Every single track belongs to a particle. 
As an incoming particle reacts with the liquid, tracks of the particles become visible as trails of (tiny) bubbles, which can be photographed.
Some of the tracks are produced by mesons, that travel through the liquid in this chamber. 
Some are created by electrons and so on. This is one of the most basic ways to make some particles detectable. But you will learn more about that on the course of our adventure. 

Before we start there is still one thing I have to tell you about my world. 
My family, the meson family is very humble and down to earth. Unlike the Baryons who, just because they have one quark more are very arrogant and bigheaded. I cannot stand them at all! 
And I can assure you this feeling is mutual. The Baryons condemn us for getting in trouble too often and being some sort of criminals since my strange cousin Kaon was arrested for CP-violation. 

*(flashback of Kaon arrest by __PNN__ (Particle News Network))*

### Part 3: Inside PNN newsroom

**News Particle**: Good evening ladies and gentleman. Welcome to our Breaking news special, where we keep you up to date about everything important that is happening in these turbulent times.
We were informed that, right now, the particle police is arresting the Kaon. It is being accused of direct CP-violation and there is strong evidence, that the Kaon is one of the particles responsible for this criminal act.


### Part 4: Inside lepton storage room

**J/&psi;:** Listen I know, this sounds bad, but whatever the baryons tell you about us, don't -

*(Door to lepton storage room clicks, the particle is alarmed and vanishes in a flash of light)*

**Comment by sarahgaiser** [comment]
A cloud chamber would look like that:
https://www.youtube.com/watch?v=i15ef618DP0
The particle tracks are pretty similar to the one in a bubble chamber.

**Comment by aaceituno01** [comment]
I my opinion the content of the script is great. There's a lot of information but it's simple and well explained, as long as we take time to present it carefully and slowly inside the game, I don't see any problem.

I also found the introduction of J/ψ a bit unnatural, so I thought of an internal game lore that could improve it:
"The particles that make up the matter and the universe need to follow some rules, so it would be nice to present an authoritarian regime that makes sure everything is working properly (in this case we have the Baryons,police,etc... that can fit the role). Due to this regime, particles from time to time have to watch some kind of "propaganda" advertising so they know their place and what do they have to do (which corresponds to the sections where the particle world is explained)."
So let's assume we take control of a meson that belongs to J/ψ's crew, that explains why you where inside the lepton storage room. Then, instead of J/ψ explaining all that stuff, they both just run away. After that, they go to the "propaganda class" as normal "people" so they don't look suspicious. This is then followed by the conversation between J/ψ and you about the Kaon CP-Violation.

I think it doesn't require a big change in the script itself or the models, etc... and adds up some cohesion to the world we're developing.
