### ISSUE TITLE
Chapter 1, first scene - news room: story board, annotations and comments

### ISSUE THREAD

**Issue by sarahgaiser** [JPsiInVR/script-and-story-board#2]
[StoryBoard_NewsRoom.pdf](https://github.com/JPsiInVR/script-and-story-board/files/6411230/StoryBoard_NewsRoom.pdf)

<img width="549" alt="StoryBoard_NewsRoom" src="https://user-images.githubusercontent.com/69592687/116811639-a343ef00-ab4a-11eb-8d0f-c850c22f4dfc.png">

**Comment by sarahgaiser** [comment]
Notes:
- @PSSteinmann volunteered to record the demo version of the news speaker particle.
- I will try to create a jingle for the PNN breaking news intro.
- @s6nadavi will provide video material of a bubble chamber for reference for PNN intro.

**Comment by s6nadavi** [comment]
### Bubble Chamber Animation

- I think it is useful to have in mind what is happening inside of the bubble chamber in terms of physics. This video is a short introduction to the principle of visualizing particles and is easy to understand. 
I suppose that knowing the basic background information will make it easier to animate the particle tracks. 
If you have any questions regarding the physics, please feel free to ask. :)

> https://www.youtube.com/watch?v=4IbyxwaItcQ


- Unfortunately, I couldn't find any animated/video material showing the bubble chamber process perfectly. Nevertheless, I think this style of animation is worth having a look at: 

> https://vimeo.com/83913189

- There would actually be two ways to design the PNN news intro:

1. We choose to present the particle visualization with some creative freedom and just shoot some different tracks across the screen, similar to the reference shown above. And we do not recreate a specific decay, but focus rather on particle tracks in a medium in general. 
2. We could use one of the most famous bubble chamber pictures of the discovery of the Omega Baryon and recreate these tracks shown down below. Since it is a decay of one specific particle the tracks would be animated in a certain order and not all of them would be visible, etc... (I could prepare these details for Adrian). 

- I think the first option of letting some tracks more or less randomly cross the screen would be more cinematic and nice to see in 3D. However, the second option would be more scientifically accurate from an educational perspective (and a nice insider amongst physicists :D ).

What do you guys think?

![omega_decay](https://user-images.githubusercontent.com/73640699/116822760-fdf83d80-ab80-11eb-84d2-518d89c4bdad.jpg)

**Comment by Ursuss21** [comment]
I guess that we can start from the first design, since it is, in my opinion, easier to implement. Then, if we would have time, we can focus on implementing the second one, which I assume, requires more specific data about the paths. For me 1st looks easier to implement, but both look cool 😃

**Comment by sarahgaiser** [comment]
I really like the idea of recreating the Omega decay! But I have to agree with @Ursuss21 that it looks a little bit more complicated. Let's use idea 1 first and maybe we have time to add the Omega decay to the visible tracks later on. It would be a very nice physics easter egg.
